clearListener(); print("Cleared in: "+getSourceFileName())


/* IMPORT FRAMEWORK */ 
filein( getFilenamePath(getSourceFileName()) + "/../MAXSCRIPT-viltools3/VilTools/rollouts-Tools/rollout-LAYERS/Lib/LayersToogleDialog/LayersToogleDialog.ms" )	--"./../MAXSCRIPT-viltools3/VilTools/rollouts-Tools/rollout-LAYERS/Lib/LayersToogleDialog/LayersToogleDialog.ms"


/* IMPORT TOOLS */ 
filein @"c:\Users\vilbur\AppData\Local\Autodesk\3dsMax\2026 - 64bit\ENU\scripts\MAXSCRIPT-DWG-Tools\DwgTools.ms"

filein @"C:\Users\vilbur\AppData\Local\Autodesk\3dsMax\2026 - 64bit\ENU\scripts\MAXSCRIPT-DWG-Tools\Tools\DwgMassImporter\DwgMassImporter.ms"

filein @"C:\Users\vilbur\AppData\Local\Autodesk\3dsMax\2026 - 64bit\ENU\scripts\MAXSCRIPT-DWG-Tools\Tools\trimSplineByVolume\trimSplineByVolume.ms"

filein @"C:\Users\vilbur\AppData\Local\Autodesk\3dsMax\2026 - 64bit\ENU\scripts\MAXSCRIPT-DWG-Tools\Tools\EdgeAlignTool\EdgeAlignTool.ms"

filein @"c:\Users\vilbur\AppData\Local\Autodesk\3dsMax\2026 - 64bit\ENU\scripts\MAXSCRIPT-DWG-Tools\Tools\TransformLockClassManager\TransformLockClassManager.ms"

filein @"C:\Users\vilbur\AppData\Local\Autodesk\3dsMax\2026 - 64bit\ENU\scripts\MAXSCRIPT-DWG-Tools\Tools\SplineToObjConvertor\SplineToObjConvertor.ms"

filein @"C:\Users\vilbur\AppData\Local\Autodesk\3dsMax\2026 - 64bit\ENU\scripts\MAXSCRIPT-DWG-Tools\Tools\SplineExtractor\SplineExtractor.ms"


